language: python
python:
 - "3.6"

# command to run tests

install:
  - pip install codecov

script:
  - python -m unittest TestTriangle
  - coverage run TestTriangle.py
  - coverage xml -i TestTriangle.py
  - coverage report TestTriangle.py


after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
