language: python
python:
 - "3.6"

# command to run tests

install:
  - pip install codecov

script:
  - python -m unittest TestTriangle
  - coverage report TestTriangle.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
