language: python
python:
 - "2.7"

# command to run tests
script:
 - python -m unittest TestTriangle
 - pip install coverage
 - coverage run TestTriangle.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
