language: python
python:
 - "2.7"

# command to run tests
script:
 - python -m unittest TestTriangle

dist: trusty
sudo: required

addons:
  sonarcloud:
  organization: "teamX-ssw567-triangle567"
  token: 7b364e5939f067309019db5fd69fc5cf58882906
  branches:
    - sonarcloud

# add the sonar-scanner command after all the other commands that you already have
script:
 - sonar-scanner
