language: python
python:
 - "2.7"

# command to run tests

install:
  - pip install codecov
  - pip install coverage

script:
 - python -m unittest TestTriangle
 - coverage run TestTriangle.py


after_success:
  - bash <(curl -s https://codecov.io/bash)
